Repository ii-nara/MBTKids, pull requests merged in 2024-11, with the labels that each got.

#74 Feat: auto scaling 구축
  .github/workflows/main.yml
  Dockerfile
  appspec.yml
  ii-api/build.gradle
  scripts/deploy.sh
Labels: ✨ Feature, 🫐 김윤수

#75 Design: 자녀 선택 버튼 수정
  ii-api/src/main/resources/static/css/parent/childSelectOrAdd.css
Labels: 🎨 Design, 🍑 김재승

#76 Design: event page
  ii-api/src/main/resources/static/css/event/events.css
  ii-api/src/main/resources/templates/event/form.html
Labels: 🎨 Design, 🥭 진승민

#78 hotfix/#136-prometheus
  ii-api/build.gradle
Labels: 🍏 조민정, ✨ Feature

#80 Feature/#67 event service
  ii-api/src/main/java/com/ureca/config/rabbitMQ/event/EventMQ.java
  ii-api/src/main/java/com/ureca/config/rabbitMQ/event/FifthEventMQ.java
  ii-api/src/main/java/com/ureca/config/rabbitMQ/event/FirstEventMQ.java
  ii-api/src/main/java/com/ureca/config/rabbitMQ/event/SecondEventMQ.java
  ii-api/src/main/java/com/ureca/config/rabbitMQ/event/ThirdEventMQ.java
  ii-api/src/main/java/com/ureca/controller/EventController.java
  ii-domain/src/main/java/com/ureca/service/EventService.java
  ii-infrastructure/src/main/java/com/ureca/entity/Enum/EventStatus.java
  ii-infrastructure/src/main/java/com/ureca/entity/EventEntity.java
Labels: ✨ Feature, 🍑 김재승

#81 Feature/#133 event redis
  ii-api/build.gradle
  ii-api/src/main/java/com/ureca/config/RedisConfig.java
  ii-api/src/main/java/com/ureca/controller/EventController.java
  ii-api/src/main/resources/templates/event/form.html
  ii-domain/build.gradle
  ii-domain/src/main/java/com/ureca/service/EventService.java
Labels: ✨ Feature, 🍓 김주호

#77 Feat: 부하테스트
  autoscale_test.js
Labels: ✅ Test, 🫐 김윤수

#83 Design: oauth login, navbar
  ii-api/src/main/resources/static/css/book/books.css
  ii-api/src/main/resources/static/css/book/detail.css
  ii-api/src/main/resources/static/css/event/events.css
  ii-api/src/main/resources/static/css/home.css
  ii-api/src/main/resources/static/css/mbti/status.css
  ii-api/src/main/resources/static/css/navbar.css
  ii-api/src/main/resources/static/css/parent/auth.css
  ii-api/src/main/resources/static/css/parent/childSelectOrAdd.css
  ii-api/src/main/resources/static/img/icon_sns_login_google.png
  ii-api/src/main/resources/static/img/icon_sns_login_kakao.png
  ii-api/src/main/resources/templates/childSelectNavbar.html
  ii-api/src/main/resources/templates/parent/childSelectOrAdd.html
  ii-api/src/main/resources/templates/parent/home.html
Labels: 🎨 Design, 🥭 진승민

#84 feature/#86-book-stats-excel
  ii-api/build.gradle
  ii-api/src/main/java/com/ureca/config/batch/BookStatsScheduler.java
  ii-api/src/main/java/com/ureca/controller/AdminController.java
  ii-api/src/main/resources/templates/admin/home.html
  ii-api/src/main/resources/templates/admin/stats.html
  ii-domain/src/main/java/com/ureca/service/BookService.java
  ii-infrastructure/src/main/java/com/ureca/entity/BookEntity.java
  ii-infrastructure/src/main/java/com/ureca/entity/BookStatsEntity.java
  ii-infrastructure/src/main/java/com/ureca/repository/BookRepository.java
  ii-infrastructure/src/main/java/com/ureca/repository/BookStatsRepository.java
Labels: 🍏 조민정, ✨ Feature

#86 Feature: event start time
  ii-api/src/main/java/com/ureca/controller/EventController.java
  ii-api/src/main/resources/templates/event/form.html
  ii-domain/src/main/java/com/ureca/service/EventService.java
Labels: ✨ Feature, 🥭 진승민

#85 Design: 성향 조회 디자인 수정
  ii-api/src/main/resources/static/css/mbti/status.css
  ii-api/src/main/resources/templates/mbti/history.html
  ii-api/src/main/resources/templates/mbti/status.html
Labels: 🎨 Design, 🍒 김은수

#87 Design: 성향 조회 디자인 누락 추가
  ii-api/src/main/resources/static/css/mbti/status.css
Labels: 🎨 Design, 🍒 김은수

#89 hotfix/#102-admin-fix
  ii-api/src/main/java/com/ureca/controller/AdminController.java
  ii-api/src/main/resources/templates/admin/stats.html
  ii-domain/src/main/java/com/ureca/service/AiService.java
  ii-domain/src/main/java/com/ureca/service/BookService.java
  ii-infrastructure/src/main/java/com/ureca/repository/BookStatsRepository.java
Labels: 🐞 BugFix, 🍏 조민정

#90 Feature: redis session storage
  ii-api/build.gradle
  ii-api/src/main/java/com/ureca/MainApplication.java
  ii-api/src/main/java/com/ureca/config/RedisSessionConfig.java
  ii-api/src/main/java/com/ureca/config/UserSecurityConfig.java
  ii-api/src/main/java/com/ureca/config/auth/PrincipalDetails.java
  ii-api/src/main/java/com/ureca/controller/ParentController.java
  ii-api/src/main/resources/static/css/mbti/test.css
  ii-api/src/main/resources/templates/event/form.html
  ii-domain/src/main/java/com/ureca/service/EventService.java
  ii-infrastructure/src/main/java/com/ureca/entity/ChildEntity.java
  ii-infrastructure/src/main/java/com/ureca/entity/FeedbackStatusEntity.java
  ii-infrastructure/src/main/java/com/ureca/entity/MbtiStatusEntity.java
  ii-infrastructure/src/main/java/com/ureca/entity/ParentEntity.java
Labels: ✨ Feature, 🥭 진승민
