Repository ii-nara/MBTKids, pull requests merged in 2024-10, with the labels that each got.

#1 Feat: childEntity 개발
  ii-infrastructure/src/main/java/com/ureca/entity/ChildEntity.java
  ii-infrastructure/src/main/java/com/ureca/repository/ChildRepository.java
Labels: ✨ Feature, 🫐 김윤수

#3 Feature/#92 recommend entity
  ii-infrastructure/build.gradle
  ii-infrastructure/src/main/java/com/ureca/entity/.gitkeep
  ii-infrastructure/src/main/java/com/ureca/entity/RecommendEntity.java
  ii-infrastructure/src/main/java/com/ureca/repository/.gitkeep
  ii-infrastructure/src/main/java/com/ureca/repository/RecommendRepository.java
  ii-infrastructure/src/main/resources/.gitkeep
  ii-infrastructure/src/test/java/com/ureca/repository/RecommendRepositoryTest.java
Labels: ✨ Feature, 🍓 김주호

#2 Feature/#93 parent entity
  ii-infrastructure/src/main/java/com/ureca/entity/ParentEntity.java
  ii-infrastructure/src/main/java/com/ureca/repository/ParentRepository.java
Labels: ✨ Feature, 🥭 진승민

#5 feature/#96-book-admin-entity-create
  ii-infrastructure/src/main/java/com/ureca/entity/AdminUserEntity.java
  ii-infrastructure/src/main/java/com/ureca/entity/BookEntity.java
  ii-infrastructure/src/main/java/com/ureca/repository/AdminUserRepository.java
  ii-infrastructure/src/main/java/com/ureca/repository/BookRepository.java
  ii-infrastructure/src/test/java/ureca/entity/AdminUserTest.java
  ii-infrastructure/src/test/java/ureca/entity/BookTest.java
Labels: 🍏 조민정, ✨ Feature

#7 Design/#101-ui-standrad
  ii-api/src/main/java/com/ureca/controller/TestController.java
  ii-api/src/main/resources/static/css/home.css
  ii-api/src/main/resources/static/css/navbar.css
  ii-api/src/main/resources/templates/home.html
  ii-api/src/main/resources/templates/navbar.html
Labels: 🎨 Design, 🍒 김은수

#11 Feat: 엔티티 테스트 설정파일 누락 추가, 의존성 삭제
  ii-infrastructure/build.gradle
  ii-infrastructure/src/test/java/ureca/TestConfiguration.java
Labels: 🐞 BugFix, 🍏 조민정

#12 Fix: 추천 테스트 코드 수정
  ii-infrastructure/src/test/java/ureca/entity/RecommendEntityTest.java
Labels: 🐞 BugFix, 🍓 김주호

#8 Feature/#61 parent signup
  build.gradle
  ii-api/build.gradle
  ii-api/src/main/java/com/ureca/controller/ParentController.java
  ii-api/src/main/resources/templates/register.html
  ii-api/src/main/resources/templates/success.html
  ii-domain/src/main/java/com/ureca/domain/Parent.java
  ii-domain/src/main/java/com/ureca/dto/ParentSignUpRequestDto.java
  ii-domain/src/main/java/com/ureca/service/ParentServiceImpl.java
  ii-domain/src/main/java/com/ureca/service/port/ParentRepository.java
  ii-domain/src/main/java/com/ureca/service/port/ParentService.java
  ii-domain/src/test/java/SignUpTest.java
  ii-infrastructure/build.gradle
  ii-infrastructure/src/main/java/com/ureca/entity/ChildEntity.java
  ii-infrastructure/src/main/java/com/ureca/entity/ParentEntity.java
  ii-infrastructure/src/main/java/com/ureca/repository/ParentJpaRepository.java
  ii-infrastructure/src/main/java/com/ureca/repository/ParentRepository.java
  ii-infrastructure/src/main/java/com/ureca/repository/ParentRepositoryImpl.java
Labels: 🧐 Review, ✨ Feature, 🥭 진승민

#14 Fix: 테스트 코드 수정
  ii-infrastructure/src/test/java/ureca/entity/FeedbackLogTest.java
  ii-infrastructure/src/test/java/ureca/entity/FeetbackStatusTest.java
  ii-infrastructure/src/test/java/ureca/entity/MbtiHistoryTest.java
  ii-infrastructure/src/test/java/ureca/entity/MbtiStatusTest.java
Labels: 🐞 BugFix, ✅ Test, 🍑 김재승

#13 feature/#54-admin-book-list
  ii-api/src/main/java/com/ureca/controller/AdminController.java
  ii-api/src/main/resources/static/css/admin/home.css
  ii-api/src/main/resources/templates/admin/home.html
  ii-domain/build.gradle
  ii-domain/src/main/java/com/ureca/dto/.gitkeep
  ii-domain/src/main/java/com/ureca/dto/BookInfo.java
  ii-domain/src/main/java/com/ureca/service/BookService.java
  ii-infrastructure/src/main/java/com/ureca/repository/BookRepository.java
  ii-infrastructure/src/main/resources/.gitkeep
  ii-infrastructure/src/test/java/ureca/entity/BookTest.java
Labels: 🍏 조민정, ✨ Feature

#15 Feature: #61 parent signup
  ii-api/src/main/java/com/ureca/controller/ParentController.java
  ii-domain/src/main/java/com/ureca/domain/Parent.java
  ii-domain/src/main/java/com/ureca/dto/ParentSignUpRequestDto.java
  ii-domain/src/main/java/com/ureca/service/ParentServiceImpl.java
  ii-domain/src/main/java/com/ureca/service/port/ParentRepository.java
  ii-domain/src/main/java/com/ureca/service/port/ParentService.java
  ii-domain/src/test/java/ParentJoinTest.java
  ii-domain/src/test/java/SignUpTest.java
  ii-infrastructure/build.gradle
  ii-infrastructure/src/main/java/com/ureca/entity/ParentEntity.java
  ii-infrastructure/src/main/java/com/ureca/repository/ParentRepositoryImpl.java
Labels: ♻️ Refactor, ✅ Test, ✨ Feature, 🥭 진승민

#17 Fix: childEntity 수정
  ii-domain/src/main/java/com/ureca/dto/MbtiStatusResponseDto.java
  ii-infrastructure/src/main/java/com/ureca/entity/ChildEntity.java
Labels: 🐞 BugFix, 🫐 김윤수

#18 Feature: Parent Login
  .idea/uiDesigner.xml
  build.gradle
  ii-api/src/main/java/com/ureca/config/.gitkeep
  ii-api/src/main/java/com/ureca/config/CustomBCryptPasswordEncoder.java
  ii-api/src/main/java/com/ureca/config/SecurityConfig.java
  ii-api/src/main/java/com/ureca/config/auth/PrincipalDetails.java
  ii-api/src/main/java/com/ureca/config/auth/PrincipalDetailsService.java
  ii-api/src/main/java/com/ureca/controller/ParentController.java
  ii-api/src/main/resources/static/css/parent/home.css
  ii-api/src/main/resources/static/css/parent/navbar.css
  ii-api/src/main/resources/templates/navbar.html
  ii-api/src/main/resources/templates/parent/home.html
  ii-api/src/main/resources/templates/parent/login.html
  ii-api/src/main/resources/templates/parent/register.html
  ii-api/src/main/resources/templates/parent/success.html
  ii-api/src/main/resources/templates/register.html
  ii-api/src/main/resources/templates/success.html
  ii-api/src/test/java/com/ureca/ParentLoginTest.java
  ii-domain/src/main/java/com/ureca/dto/ParentSignUpRequestDto.java
  ii-domain/src/main/java/com/ureca/service/ParentServiceImpl.java
  ii-domain/src/test/java/ParentJoinTest.java
  ii-infrastructure/src/main/java/com/ureca/repository/ParentJpaRepository.java
Labels: ✅ Test, ✨ Feature, 🥭 진승민

#22 Fix: childEntity, MbtiStatusEntity 수정
  ii-infrastructure/src/main/java/com/ureca/entity/ChildEntity.java
  ii-infrastructure/src/main/java/com/ureca/entity/MbtiStatusEntity.java
  ii-infrastructure/src/test/java/ureca/entity/MbtiStatusTest.java
Labels: 🐞 BugFix, 🍑 김재승

#19 Feature/#30 mbti test logic
  build.gradle
  ii-api/build.gradle
  ii-api/src/main/java/com/ureca/controller/MbtiTestController.java
  ii-api/src/main/resources/static/css/mbti/result.css
  ii-api/src/main/resources/static/css/mbti/test.css
  ii-api/src/main/resources/static/js/mbti/test.js
  ii-api/src/main/resources/templates/mbti/result.html
  ii-api/src/main/resources/templates/mbti/test.html
  ii-domain/src/main/java/com/ureca/domain/MbtiQuestion.java
  ii-domain/src/main/java/com/ureca/domain/MbtiQuestionProvider.java
  ii-domain/src/main/java/com/ureca/dto/MbtiResponseDTO.java
  ii-domain/src/main/java/com/ureca/service/MbtiTestService.java
Labels: 🎨 Design, 🧐 Review, ✨ Feature, 📝 Docs, 🍒 김은수

#21 Feature: #65 child create
  ii-api/src/main/java/com/ureca/config/SecurityConfig.java
  ii-api/src/main/java/com/ureca/config/auth/PrincipalDetailsService.java
  ii-api/src/main/java/com/ureca/controller/ParentController.java
  ii-api/src/main/resources/static/css/parent/home.css
  ii-api/src/main/resources/static/css/parent/home.css.map
  ii-api/src/main/resources/static/css/parent/home.scss
  ii-api/src/main/resources/static/js/parent/home.js
  ii-api/src/main/resources/templates/parent/addChild.html
  ii-api/src/main/resources/templates/parent/childSelectOrAdd.html
  ii-api/src/main/resources/templates/parent/home.html
  ii-api/src/main/resources/templates/parent/login.html
  ii-api/src/main/resources/templates/parent/register.html
  ii-domain/src/main/java/com/ureca/dto/ChildCreateDto.java
  ii-domain/src/main/java/com/ureca/service/ChildAddServiceImpl.java
Labels: ✨ Feature, 🥭 진승민

#23 feature/#57,55-admin-book-detail-search
  ii-api/src/main/java/com/ureca/controller/AdminController.java
  ii-api/src/main/java/com/ureca/dto/ReqBookInfo.java
  ii-api/src/main/resources/static/css/admin/navbar.css
  ii-api/src/main/resources/templates/admin/detail.html
  ii-api/src/main/resources/templates/admin/home.html
  ii-domain/src/main/java/com/ureca/dto/ResBookInfo.java
  ii-domain/src/main/java/com/ureca/service/BookService.java
  ii-infrastructure/src/main/java/com/ureca/dto/BookInfo.java
  ii-infrastructure/src/main/java/com/ureca/entity/BookEntity.java
  ii-infrastructure/src/main/java/com/ureca/repository/BookRepository.java
Labels: 🍏 조민정, ✨ Feature

#25 Fix: jpa 의존성을 전체모듈로 이동
  build.gradle
  ii-domain/build.gradle
  ii-infrastructure/build.gradle
Labels: 🐞 BugFix, 🍒 김은수

#24 Feature/#14 recommend books
  .gitignore
  ii-api/src/main/java/com/ureca/controller/HomeController.java
  ii-api/src/main/resources/templates/book/books.html
  ii-api/src/main/resources/templates/home.html
  ii-domain/src/main/java/com/ureca/dto/BookPage.java
  ii-domain/src/main/java/com/ureca/service/RecommendService.java
  ii-infrastructure/src/main/java/com/ureca/entity/RecommendEntity.java
  ii-infrastructure/src/main/java/com/ureca/repository/BookRepository.java
  ii-infrastructure/src/main/java/com/ureca/repository/RecommendRepository.java
  ii-infrastructure/src/test/java/ureca/entity/RecommendEntityTest.java
Labels: ✨ Feature, 🍓 김주호

#26 Fix: 도서 컬럼 변경내용 반영
  ii-api/src/main/resources/templates/book/books.html
  ii-api/src/main/resources/templates/home.html
  ii-domain/src/main/java/com/ureca/service/RecommendService.java
Labels: 🐞 BugFix, 🍓 김주호

#27 Feat: Child Select Service
  ii-api/src/main/java/com/ureca/config/SecurityConfig.java
  ii-api/src/main/java/com/ureca/config/auth/PrincipalDetails.java
  ii-api/src/main/java/com/ureca/controller/ParentController.java
  ii-api/src/main/java/com/ureca/dto/.gitkeep
  ii-api/src/main/resources/templates/parent/addChild.html
  ii-api/src/main/resources/templates/parent/childProfile.html
  ii-api/src/main/resources/templates/parent/childSelectOrAdd.html
  ii-domain/src/main/java/com/ureca/service/ChildAddServiceImpl.java
  ii-infrastructure/src/main/java/com/ureca/repository/ChildRepository.java
Labels: ✨ Feature, 🥭 진승민

#20 Feat: MbtiManagementService 개발
  ii-domain/src/main/java/com/ureca/service/MbtiManagementService.java
  ii-infrastructure/src/main/java/com/ureca/entity/ChildEntity.java
  ii-infrastructure/src/main/java/com/ureca/entity/MbtiDeleteEntity.java
  ii-infrastructure/src/main/java/com/ureca/repository/MbtiDeleteRepository.java
  ii-infrastructure/src/main/java/com/ureca/repository/MbtiHistoryRepository.java
  ii-infrastructure/src/main/java/com/ureca/repository/MbtiStatusRepository.java
Labels: ✨ Feature, 🫐 김윤수

#28 Feature/#107 mbti result get
  ii-api/src/main/java/com/ureca/controller/MbtiTestController.java
  ii-api/src/main/resources/static/css/mbti/result.css
  ii-api/src/main/resources/templates/mbti/result.html
  ii-domain/src/main/java/com/ureca/dto/MbtiInfoResponseDto.java
  ii-domain/src/main/java/com/ureca/service/MbtiInfoService.java
  ii-infrastructure/src/main/java/com/ureca/entity/MbtiInfoEntity.java
  ii-infrastructure/src/main/java/com/ureca/repository/MbtiInfoRepository.java
Labels: ♻️ Refactor, 🎨 Design, ✨ Feature, 🍒 김은수

#29 Fix: mbtiRepository 오류 수정
  ii-api/src/main/java/com/ureca/controller/MbtiTestController.java
  ii-domain/src/main/java/com/ureca/dto/MbtiTestResponseDTO.java
  ii-domain/src/main/java/com/ureca/service/MbtiManagementService.java
  ii-domain/src/main/java/com/ureca/service/MbtiTestService.java
  ii-infrastructure/src/main/java/com/ureca/repository/MbtiStatusRepository.java
Labels: 🐞 BugFix, 🫐 김윤수

#30 Fix: import 구문 추가
  ii-api/src/main/java/com/ureca/controller/MbtiTestController.java
Labels: 🐞 BugFix, 🍒 김은수

#31 Fix/Feedback 관련 엔티티 수정
  ii-infrastructure/src/main/java/com/ureca/entity/Enum/LikeStatus.java
  ii-infrastructure/src/main/java/com/ureca/entity/Enum/LikeStatusConverter.java
  ii-infrastructure/src/main/java/com/ureca/entity/FeedbackLogEntity.java
  ii-infrastructure/src/main/java/com/ureca/entity/FeedbackStatusEntity.java
  ii-infrastructure/src/main/java/com/ureca/entity/MbtiHistoryEntity.java
  ii-infrastructure/src/main/java/com/ureca/entity/MbtiStatusEntity.java
  ii-infrastructure/src/main/java/com/ureca/repository/FeedbackLogRepository.java
  ii-infrastructure/src/test/java/ureca/entity/FeedbackLogTest.java
  ii-infrastructure/src/test/java/ureca/entity/FeetbackStatusTest.java
  ii-infrastructure/src/test/java/ureca/entity/MbtiHistoryTest.java
  ii-infrastructure/src/test/java/ureca/entity/MbtiStatusTest.java
Labels: 🐞 BugFix, 🍑 김재승

#32 Fix: MbtiManagementService, MbtiStatusEntity, ChildEntity 수정
  ii-domain/src/main/java/com/ureca/service/ChildAddServiceImpl.java
  ii-domain/src/main/java/com/ureca/service/MbtiManagementService.java
  ii-infrastructure/src/main/java/com/ureca/entity/ChildEntity.java
  ii-infrastructure/src/main/java/com/ureca/entity/MbtiDeleteEntity.java
  ii-infrastructure/src/main/java/com/ureca/entity/MbtiStatusEntity.java
  ii-infrastructure/src/main/java/com/ureca/repository/MbtiDeleteRepository.java
  ii-infrastructure/src/main/java/com/ureca/repository/MbtiHistoryRepository.java
Labels: 🐞 BugFix, 🫐 김윤수

#38 Feature/#32 mbti test insert
  ii-api/src/main/java/com/ureca/controller/MbtiTestController.java
  ii-api/src/main/resources/templates/mbti/result.html
  ii-domain/src/main/java/com/ureca/dto/MbtiStatusRequestDto.java
  ii-domain/src/main/java/com/ureca/dto/MbtiTestResponseDTO.java
  ii-domain/src/main/java/com/ureca/model/MbtiQuestion.java
  ii-domain/src/main/java/com/ureca/model/MbtiQuestionProvider.java
  ii-domain/src/main/java/com/ureca/service/MbtiManagementService.java
  ii-domain/src/main/java/com/ureca/service/MbtiTestService.java
  ii-infrastructure/src/main/java/com/ureca/entity/ChildEntity.java
  ii-infrastructure/src/main/java/com/ureca/entity/MbtiHistoryEntity.java
  ii-infrastructure/src/main/java/com/ureca/entity/MbtiStatusEntity.java
Labels: ♻️ Refactor, 🐞 BugFix, ✨ Feature, 🍒 김은수

#33 feature/#112-openapi-book-data
  ii-api/src/main/java/com/ureca/controller/AdminController.java
  ii-domain/src/main/java/com/ureca/service/OpenApiService.java
  ii-infrastructure/src/main/java/com/ureca/entity/BookEntity.java
  ii-infrastructure/src/test/java/ureca/entity/BookTest.java
Labels: 🍏 조민정, ✨ Feature

#36 feature/#53-admin-book-delete
  ii-api/src/main/java/com/ureca/controller/AdminController.java
  ii-api/src/main/resources/templates/admin/detail.html
  ii-domain/src/main/java/com/ureca/service/BookService.java
Labels: 🍏 조민정, ✨ Feature

#37 Feature/#106 recommend session
  ii-api/src/main/java/com/ureca/controller/HomeController.java
  ii-api/src/main/resources/templates/home.html
  ii-domain/src/main/java/com/ureca/constant/RecommendationType.java
  ii-domain/src/main/java/com/ureca/service/RecommendService.java
Labels: ♻️ Refactor, ✨ Feature, 🍓 김주호

#39 Feature/#114 fix recommend
  ii-api/src/main/resources/templates/home.html
  ii-infrastructure/src/main/java/com/ureca/repository/BookRepository.java
Labels: 🍓 김주호

#41 Feature/#34 feedback logic
  ii-api/build.gradle
  ii-api/src/main/java/com/ureca/controller/HomeController.java
  ii-api/src/main/resources/templates/book/detail.html
  ii-api/src/test/java/com/ureca/FeedBackConcurrencyTest.java
  ii-domain/build.gradle
  ii-domain/src/main/java/com/ureca/dto/RequestFeedbackDto.java
  ii-domain/src/main/java/com/ureca/dto/ResBookInfo.java
  ii-domain/src/main/java/com/ureca/dto/ResponseFeedbackDto.java
  ii-domain/src/main/java/com/ureca/service/FeedbackComponentService.java
  ii-domain/src/main/java/com/ureca/service/FeedbackManagementService.java
  ii-domain/src/main/java/com/ureca/service/MbtiManagementService.java
  ii-domain/src/test/java/ureca/FeedbackServiceTest/addFeedbackSyncTest.java
  ii-domain/src/test/java/ureca/FeedbackServiceTest/addFeedbackTest.java
  ii-domain/src/test/java/ureca/FeedbackServiceTest/updateFeedbackStatusTest.java
  ii-domain/src/test/java/ureca/FeedbackServiceTest/updateMbtiStatusTest.java
  ii-infrastructure/build.gradle
  ii-infrastructure/src/main/java/com/ureca/config/RabbitMQConfig.java
  ii-infrastructure/src/main/java/com/ureca/entity/FeedbackStatusEntity.java
  ii-infrastructure/src/main/java/com/ureca/repository/FeedbackStatusRepository.java
  ii-infrastructure/src/main/java/com/ureca/repository/MbtiHistoryRepository.java
Labels: 🙋‍♂️ Question, ✨ Feature, 🍑 김재승

#42 Fix: rabbitMQ 임시 비활성화
  ii-api/src/main/java/com/ureca/controller/HomeController.java
  ii-domain/src/main/java/com/ureca/service/FeedbackComponentService.java
  ii-infrastructure/src/main/java/com/ureca/config/RabbitMQConfig.java
Labels: 🐞 BugFix, 🍑 김재승

#47 Feat: 자녀성향과 히스토리 조회 화면 개발
  ii-api/build.gradle
  ii-api/src/main/java/com/ureca/MainApplication.java
  ii-api/src/main/java/com/ureca/config/batch/BatchConfig.java
  ii-api/src/main/java/com/ureca/config/batch/BatchScheduler.java
  ii-api/src/main/java/com/ureca/controller/MbtiManagementController.java
  ii-api/src/main/resources/static/css/mbti/history.css
  ii-api/src/main/resources/static/css/mbti/status.css
  ii-api/src/main/resources/templates/mbti/history.html
  ii-api/src/main/resources/templates/mbti/status.html
  ii-api/src/main/resources/templates/navbar.html
  ii-domain/src/main/java/com/ureca/dto/MbtiHistoryResponseDto.java
  ii-domain/src/main/java/com/ureca/service/MbtiManagementService.java
  ii-infrastructure/src/main/java/com/ureca/entity/MbtiStatusEntity.java
  ii-infrastructure/src/main/java/com/ureca/repository/MbtiStatusRepository.java
Labels: ✨ Feature, 🫐 김윤수

#48 Feat: CI/CD 구축
  appspec.yml
  scripts/deploy.sh
Labels: ✨ Feature, 🫐 김윤수

#44 Feat: main.yml 생성
  .github/workflows/main.yml
Labels: ✨ Feature, 🫐 김윤수

#50 Feature/#109 add RabbitMQ
  ii-api/src/main/java/com/ureca/config/RabbitMQConfig.java
  ii-api/src/main/java/com/ureca/controller/HomeController.java
  ii-api/src/test/java/com/ureca/FeedBackConcurrencyTest.java
  ii-domain/src/main/java/com/ureca/service/FeedbackComponentService.java
  ii-domain/src/main/java/com/ureca/service/FeedbackManagementService.java
  ii-infrastructure/src/main/java/com/ureca/config/RabbitMQConfig.java
Labels: ♻️ Refactor, ✨ Feature, 🍑 김재승

#52 Fix/rename service
  ii-domain/src/main/java/com/ureca/service/FeedbackComponentService.java
  ii-domain/src/test/java/ureca/FeedbackServiceTest/addFeedbackSyncTest.java
  ii-domain/src/test/java/ureca/FeedbackServiceTest/addFeedbackTest.java
  ii-domain/src/test/java/ureca/FeedbackServiceTest/updateMbtiStatusTest.java
Labels: 🐞 BugFix, 🍑 김재승

#56 feature/#51-52-book-register-update-s3
  ii-api/build.gradle
  ii-api/src/main/java/com/ureca/config/S3Config.java
  ii-api/src/main/java/com/ureca/controller/AdminController.java
  ii-api/src/main/resources/templates/admin/detail.html
  ii-domain/src/main/java/com/ureca/dto/ReqBookInfo.java
  ii-domain/src/main/java/com/ureca/dto/ResBookDetail.java
  ii-domain/src/main/java/com/ureca/service/BookService.java
Labels: 🍏 조민정, ✨ Feature

#57 Feature/#63 oauth2 kakao
  ii-api/src/main/java/com/ureca/config/UserSecurityConfig.java
  ii-api/src/main/java/com/ureca/config/auth/PrincipalDetails.java
  ii-api/src/main/java/com/ureca/config/oauth/PrincipalOauth2UserService.java
  ii-api/src/main/java/com/ureca/config/oauth/provider/KakaoUserInfo.java
  ii-api/src/main/java/com/ureca/controller/ParentController.java
  ii-api/src/main/resources/static/css/parent/addChild.css
  ii-api/src/main/resources/static/css/parent/additionalForm.css
  ii-api/src/main/resources/static/css/parent/auth.css
  ii-api/src/main/resources/static/css/parent/childSelectOrAdd.css
  ii-api/src/main/resources/static/css/parent/home.css
  ii-api/src/main/resources/static/css/parent/home.css.map
  ii-api/src/main/resources/static/css/parent/home.scss
  ii-api/src/main/resources/static/css/parent/navbar.css
  ii-api/src/main/resources/static/img/kakao_login_small.png
  ii-api/src/main/resources/templates/parent/addChild.html
  ii-api/src/main/resources/templates/parent/additionalForm.html
  ii-api/src/main/resources/templates/parent/childSelectOrAdd.html
  ii-api/src/main/resources/templates/parent/home.html
Labels: 🎨 Design, ✨ Feature, 🥭 진승민

#58 Fix: CI/CD 수정, HomeController 수정
  .github/workflows/main.yml
  ii-api/src/main/java/com/ureca/controller/HomeController.java
Labels: 🐞 BugFix, 🫐 김윤수

#59 Hotfix/fix navbar home html
  ii-api/src/main/resources/templates/home.html
  ii-api/src/main/resources/templates/navbar.html
Labels: 🎨 Design, 🍓 김주호

#60 feature/#79-home-book-search
  ii-api/src/main/java/com/ureca/controller/HomeController.java
  ii-api/src/main/resources/templates/book/list.html
  ii-api/src/main/resources/templates/home.html
  ii-domain/src/main/java/com/ureca/service/BookService.java
  ii-infrastructure/src/main/java/com/ureca/repository/BookRepository.java
Labels: 🍏 조민정, ✨ Feature

#61 Fix: HomeController 수정
  ii-api/src/main/java/com/ureca/controller/HomeController.java
Labels: 🐞 BugFix, 🫐 김윤수

#62 Design: home,book css
  ii-api/src/main/java/com/ureca/controller/HomeController.java
  ii-api/src/main/resources/static/css/book/books.css
  ii-api/src/main/resources/static/css/book/detail.css
  ii-api/src/main/resources/static/css/book/list.css
  ii-api/src/main/resources/static/css/home.css
  ii-api/src/main/resources/templates/admin/loginForm.html
  ii-api/src/main/resources/templates/book/books.html
  ii-api/src/main/resources/templates/book/detail.html
  ii-api/src/main/resources/templates/book/list.html
  ii-api/src/main/resources/templates/home.html
Labels: 🎨 Design, 🥭 진승민

#64 Fix: HomeController 수정
  ii-api/src/main/java/com/ureca/controller/HomeController.java
Labels: 🐞 BugFix, 🫐 김윤수

#66 hotfix/#57-admin-register-view
  ii-api/src/main/resources/templates/admin/detail.html
Labels: 🐞 BugFix

#65 fix/#79-book-list-fix
  ii-api/src/main/resources/templates/navbar.html
Labels: 🐞 BugFix, 🫐 김윤수

#71 Fix: 추천 쿼리 수정
  ii-infrastructure/src/main/java/com/ureca/repository/BookRepository.java
Labels: 🐞 BugFix, 🍓 김주호

#70 Refactor: rabbitMQ 리팩토링
  ii-api/src/main/java/com/ureca/config/rabbitMQ/BaseRabbitMQConfig.java
  ii-api/src/main/java/com/ureca/config/rabbitMQ/FeedbackRabbitMQConfig.java
  ii-api/src/main/java/com/ureca/config/rabbitMQ/event/EventRabbitMQConfig.java
  ii-api/src/main/java/com/ureca/config/rabbitMQ/event/FifthEventMQ.java
  ii-api/src/main/java/com/ureca/config/rabbitMQ/event/FirstEventMQ.java
  ii-api/src/main/java/com/ureca/config/rabbitMQ/event/FourthEventMQ.java
  ii-api/src/main/java/com/ureca/config/rabbitMQ/event/SecondEventMQ.java
  ii-api/src/main/java/com/ureca/config/rabbitMQ/event/ThirdEventMQ.java
  ii-api/src/main/java/com/ureca/controller/HomeController.java
  ii-domain/src/main/java/com/ureca/service/FeedbackComponentService.java
Labels: ♻️ Refactor, ✨ Feature, 🍑 김재승

#69 Fix: navbar.html 수정
  ii-api/src/main/resources/templates/navbar.html
Labels: 🐞 BugFix, 🫐 김윤수
